### ISSUE TITLE
pwd is breaking my package build

### ISSUE THREAD

**Issue by michaelinipop** [memsharded/conan-protobuf#4]
self.run("pwd") in the test file breaks in windows

**Comment by memsharded** [comment]
I see, yes, that is not good. I will have a look and try to fix it. Meanwhile, you can try running it in Windows in a terminal that supports POSIX commands. I work a lot in windows and I use cmder.

Thanks very much for reporting.

**Comment by memsharded** [comment]
I didn't realize, it was just a dummy, unused thing, so I have just removed and pushed to github, so after a while that it passes CI in travis and appveyor, it will be in conan.io too. Thanks again!

**Comment by michaelinipop** [comment]
No thank you yeah I figured it had no importance.
